# Theme settings
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
doks:
    baseurl:
    color_theme: purple # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            image: 
        nav:
            - item_name: Home
              item_url: '/'
    footer:
        content:
            logo:
                text: Teaching Resources
                image:
            copyright: 'Contact: <a href="mailto:danicassol@gmail.com">danicassol@gmail.com</a> </br> ©2020 Daniela Cassol. All rights reserved.'
        social_list:
            - network_name: github
              profile_url: 'https://www.github.com/dcassol'
    google_analytics:
        tracking_code: UA-160203747-1
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

plugins:
- jekyll-latex

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
